name: Website Builder

# Run this workflow every time a new commit pushed to your repository,
# and periodically, to pick up any other updates that may have occurred - 
# e.g. in the data repository
on: 
  push:
    branches:
      - main
  schedule:
    # Run daily at 1pm
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 13 * * *'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  website-builder:
    # Name the Job
    name: Build the website from this repository
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the submodules as well
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Prepare the website directory
      - name: Copy dependencies to Website directory
        run: |
          echo `pwd`
          bash ./build/website/copy-assets.sh
        shell: bash

      # Standard usage of the plugin as described on https://jekyllrb.com/docs/continuous-integration/github-actions/
      # on 2021-01-31
      - uses:  helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: 'website'
          target_branch: 'gh-pages'
          jekyll_env: production