name: Website Builder

# Run this workflow every time a new commit pushed to your repository,
# and periodically, to pick up any other updates that may have occurred - 
# e.g. in the data repository
on: 
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  website-builder:
    # Name the Job
    name: Build the website from this repository
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs a script
      - name: Build Website
        run: |
          echo "Hello" && \
          echo `pwd`
          bash build.sh
        shell: bash
        working-directory: "./website"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: "./website/site" # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch